export const ADD_INGREDIENT ='ADD_INGREDIENT';
export const REMOVE_INGREDIENT ='REMOVE_INGREDIENT';
export const SET_INGREDIENT='SET_INGREDIENT';
export const FETCH_INGREDIENTS_FAILED ='FETCH_INGREDIENTS_FAILED';

export const PURCHASEE_BURGER_START='PURCHASEE_BURGER_START';
export const PURCHASEE_BURGER_SUCCESS='PURCHASEE_BURGER_SUCCESS';
export const PURCHASEE_BURGER_FAIL='PURCHASEE_BURGER_FAIL';
export const PURCHASE_INIT='PURCHASE_INIT';

export const FETCH_ORDER_START='FETCH_ORDER_START';
export const FETCH_ORDER_SUCCESS='FETCH_ORDER_SUCCESS';
export const FETCH_ORDER_FAIL='FETCH_ORDER_FAIL';

export const AUTH_START='AUTH_START';
export const AUTH_SUCCESS='AUTH_SUCCESS';
export const AUTH_FAIL='AUTH_FAIL';


export const AUTH_LOGGOUT='AUTH_LOGGOUT';

export const SET_AUTH_REDIRECT_PATH='SET_AUTH_REDIRECT_PATH';